#!/usr/bin/ruby -w

require 'test/tc_mock_rand'
require 'test/tc_setting'
require 'test/tc_grammar'
require 'test/tc_abnf_tokenizer'
require 'test/tc_abnf_parser'
require 'test/tc_abnf_renderer'
require 'test/tc_mappers'
require 'test/tc_generators'
require 'test/tc_validator'
require 'test/tc_pareto'
require 'test/tc_crossover'
require 'test/tc_mutation'
require 'test/tc_random_init'
require 'test/tc_evaluator'
require 'test/tc_ranking.rb'
