---
algorithm:
  class: Generational

  population_size: 500
  elite_size: 5
  crossover_probability: 0.9
  mutation_probability: 0.1

  termination:
    max_steps: 100
    on_individual: :stopping_condition

grammar:
  class: AbnfFile
  initialize: "'sample/toy_regression/grammar.abnf'"

mapper:
  class: DepthFirst
  wraps_to_fail: 3 

elite_rank:
  class: Ranking
  order_by: :error  #optional
  direction: :minimize #optional 

selection:
  class: RankRoulette
selection_rank: #optional
  class: Ranking
        
crossover:
  class: Crossover
  margin: 1

mutation:
  class: Mutation
  magnitude: 16 # same as individual.init_magnitude

store:
  class: Store
  filename: ./toy_regression.store

report:
  class: ToyReport
  require: sample/toy_regression/toy_report.rb

individual:
  class: ToyIndividual
  require: sample/toy_regression/toy_individual.rb
  init_magnitude: 16 #same as mutation.magnitude
  init_length: 8
